version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: moonshot
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: moonshot
      MONGO_INITDB_ROOT_PASSWORD: moonshot
    ports:
      - "27017:27017"